[2023-09-26 04:24:19,347] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.generate_dim_data manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:24:19,355] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.generate_dim_data manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:24:19,356] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:24:19,356] {taskinstance.py:1357} INFO - Starting attempt 9 of 9
[2023-09-26 04:24:19,356] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:24:19,370] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): generate_dim_data> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 04:24:19,375] {standard_task_runner.py:52} INFO - Started process 1309 to run task
[2023-09-26 04:24:19,377] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'generate_dim_data', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmp0gkgf_1g', '--error-file', '/tmp/tmpjshb25kg']
[2023-09-26 04:24:19,378] {standard_task_runner.py:80} INFO - Job 26: Subtask generate_dim_data
[2023-09-26 04:24:19,436] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.generate_dim_data manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 04:24:19,515] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=generate_dim_data
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 04:24:20,058] {python.py:173} INFO - Done. Returned value was: None
[2023-09-26 04:24:20,076] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=1_dags, task_id=generate_dim_data, execution_date=20230926T025818, start_date=20230926T042419, end_date=20230926T042420
[2023-09-26 04:24:20,112] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-09-26 04:24:20,146] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
